services:
  mysqldb-auth:
    image: mysql:8.0.22
    container_name: mysqldb-auth
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: example
    ports:
      - "3307:3306"
    volumes:
      - mysql-auth-data:/var/lib/mysql
    networks:
      - stock-app-network

  auth-service:
    container_name: auth-service
    build:
      context: .
      dockerfile: DockerfileWithDependency
      args:
        DEPENDENCY: auth-api
        SERVICE: auth-service
    ports:
      - "8080:8080"
    depends_on:
      - mysqldb-auth
    networks:
      - stock-app-network
    restart: on-failure
    environment:
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb-auth:3306/auth?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true

volumes:
  mysql-auth-data:

networks:
  stock-app-network: